services:

  recruit:
    container_name: recruit_php
    image: recruit/php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/srv:cached
    tty: true
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  default:
    driver: bridge